name = "kf3notif"
main = "./dist/index.js"
compatibility_date = "2024-04-01"
compatibility_flags = [ "nodejs_compat" ]

[placement]
mode = "smart"

[assets]
directory = "./dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "KF3_NOTIF_CACHE"
id = "07df384a6c6e40039d42e663e6a13b7a"

[[r2_buckets]]
binding = "KF3_NOTIF_DATA"
bucket_name = "kf3-notif-data"
