name = "kf3notif"
main = "./dist/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[version_metadata]
binding = "CF_VERSION_METADATA"

[assets]
directory = "./dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "KF3_NOTIF_CACHE"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "KF3_NOTIF_DATA"
bucket_name = "kf3-notif-data"

[[r2_buckets]]
binding = "KF3_NOTIF_BACKUP"
bucket_name = "kf3-notif-backup"

[[queues.producers]]
binding = "KF3_ARCHIVE_UPDATE_QUEUE"
queue = "kf3-notif-archive-update"

[[queues.consumers]]
queue = "kf3-notif-archive-update"
max_batch_size = 1
max_batch_timeout = 1
max_retries = 3
max_concurrency = 1

[triggers]
crons = ["15 18 * * *"]

[observability]
enabled = true

[observability.logs]
enabled = true
head_sampling_rate = 1

[observability.traces]
enabled = true
head_sampling_rate = 1

[[durable_objects.bindings]]
name = "KF3_REFRESH_COORDINATOR"
class_name = "NewsRefreshCoordinator"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["NewsRefreshCoordinator"]
